### ISSUE TITLE
New install failing on Windows

### ISSUE THREAD

**Issue by alabella19** [MesquiteProject/MesquiteCore#101]
Longtime user of Mesquite - Just purchased a new computer and cannot install Mesquite

I downloaded the zipped Mesquite and changed the DPI settings as instructed

System: Windows 10 v 20H2 build 19042.1052
Java: Version 8 Update 291 (build 1.8.0_291-b10)

Dialog box:
`
28 June 2021,  14:08 CDT
Running under Java 16.0.1; virtual machine by Oracle Corporation on Windows 10 10.0 (architecture: amd64)
User: abiga
 

(Following stack trace from object of class: class mesquite.Mesquite)
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils
	at mesquite.lib.StringUtil.protectForXML(StringUtil.java:1558)
	at mesquite.lib.StringUtil.appendXMLTag(StringUtil.java:1626)
	at mesquite.Mesquite.preparePreferencesForXML(Mesquite.java:1072)
	at mesquite.lib.MesquiteModule.storePreferences(MesquiteModule.java:912)
	at mesquite.Mesquite.init(Mesquite.java:507)
	at mesquite.Mesquite.<init>(Mesquite.java:2574)
	at mesquite.Mesquite.main(Mesquite.java:2805)
	at mesquite.Mesquite.mainViaStarter(Mesquite.java:2798)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at start.Mesquite.startMesquite(Mesquite.java:128)
	at start.Mesquite.main(Mesquite.java:59)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringEscapeUtils
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 14 more

C:\Users\abiga\Documents\BioInf\Mesquite_Folder\
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils
Error caught in Mesquite
mesquite.lib.StringUtil.protectForXML(StringUtil.java:1558)
mesquite.lib.StringUtil.appendXMLTag(StringUtil.java:1626)
mesquite.Mesquite.preparePreferencesForXML(Mesquite.java:1072)
mesquite.lib.MesquiteModule.storePreferences(MesquiteModule.java:912)
mesquite.Mesquite.init(Mesquite.java:507)
mesquite.Mesquite.<init>(Mesquite.java:2574)
mesquite.Mesquite.main(Mesquite.java:2805)
mesquite.Mesquite.mainViaStarter(Mesquite.java:2798)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:567)
start.Mesquite.startMesquite(Mesquite.java:128)
start.Mesquite.main(Mesquite.java:59)

Note: (Mesquite): An error indicates that you may have an incomplete version of Mesquite, or a package installed that is incompatible with this version of Mesquite. Please check your add-on packages like Zephyr, Chromaseq, etc. to ensure they are up to date, and that you are using an up to date version of Mesquite.  You may need to reinstall Mesquite.`

**Comment by wmaddisn** [comment]
Apologies for the delay. Could you try the following: go into Mesquite_Folder/jars and delete (or best, move somewhere else) the file commons-lang-2.3.jar? Then try to start it.

**Comment by alabella19** [comment]
Unfortunately I get an identical error message as before.

**Comment by wmaddisn** [comment]
Thanks! In the jars folder, do you see a file with name commons-lang3-...?

Your earlier report indicated that you have Java 1.8, but you list the dialog box as saying "Running under Java 16.0.1; virtual machine by Oracle Corporation on Windows 10 10.0 (architecture: amd64)", which means Java 1.6. Do you know if you have multiple versions of Java?

**Comment by alabella19** [comment]
And yes there is a comons-lang3 file. 

Looks like I have two versions of Java and the 16.0.1 version is what's being run 

04/23/2021  06:42 PM    <DIR>          jdk-16.0.1
04/23/2021  06:27 PM    <DIR>          jre1.8.0_291

PATH
PATH=C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\jEdit;C:\Program Files\MATLAB\MATLAB Runtime\v90\runtime\win64;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\Users\abiga\AppData\Local\Microsoft\WindowsApps

So when I ask for the java version in the command window I get
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

Thanks!

**Comment by wmaddisn** [comment]
I suspect 16.0.1 is the problem. Do you know the path to java 1.8? If you do, could you move Mesquite_Start_Script.bat out of its folder into the containing one (Mesquite_Folder), and edit it to put the full path to java instead of just “java”?  

If you double click that, does Mesquite start?

Wayne

**Comment by wmaddisn** [comment]
We've found the problem with Java 16 and should have a fix available soon. It might require that you start Mesquite via the batch file instead of the executable.

**Comment by wmaddisn** [comment]
Could you go to https://drive.google.com/drive/folders/1wlxRO0b06uyxshyjqMD_Rk52FtyK5aTp?usp=sharing and download the Mesquite_Starter_K2.exe (or the K8 version)?  But that in your Mesquite_Folder, and try to start it up. Does it succeed in starting Mesquite?

(Not sure if your system will let you start an exe downloaded in this way, but let's try it, and if not, I''ll try to get it to you to test in a different way.)
Thanks,
Wayne

**Comment by alabella19** [comment]
It works! I downloaded it, put it in the folder and executed it - I had to approve it to "run away".

I tested by opening files and editing. Everything seems great.
Thank you so much!

**Comment by wmaddisn** [comment]
We just released a new full version that has this fix in it. Not too many bug fixes and features; mostly about these startup issues.

**Comment by alabella19** [comment]
Thank you so much!
